apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', "while :; do echo 'myapp-container is running!'; sleep 3; done"]
  initContainers:
    - name: init-a
      image: busybox:1.28
      command: ['sh', '-c', "for i in 1 2 3 4 5 6 7 8 9 10; do echo 'init-a initializing...'; sleep 2; done"]
    - name: init-b
      image: busybox:1.28
      command: ['sh', '-c', "for i in 1 2 3 4 5 6 7 8 9 10; do echo 'init-b initializing...'; sleep 2; done"]